### ISSUE TITLE
Add cookie controls

### ISSUE THREAD

**Issue by mattdebont** [jncc/deli#28]
We need to allow people to opt out of cookies from the deli sites

**Comment by completer** [comment]
Investigating what we need / will work with the current set up. Currently the only cookies are Google Analytics.

**Comment by completer** [comment]
![deli-cookies-notice](https://user-images.githubusercontent.com/917606/31080886-f647ce90-a781-11e7-9dfa-01155f6fa787.png)

Adding plain text message.

**Comment by completer** [comment]
https://ico.org.uk/for-organisations/guide-to-pecr/cookies-and-similar-technologies/ 
Still need to provide an explanation of exactly what the cookies (analytics) are doing.

**Comment by LynnHeeley** [comment]
replace with #32
