### ISSUE TITLE
Privacy Statement- Scottish Lidar

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/deli#39]
Add a hyperlink statement to the Scottish Lidar portal to link to a privacy statement. See statisticians site for example text and hyperlink. Home for link: http://statistics.gov.scot/home (bottom right grouped with cookies statement), and actual statement on this page: http://statistics.gov.scot/policy#privacy

**Comment by LynnHeeley** [comment]
due date COP 24th May

**Comment by completer** [comment]
So I will add the text:

```
Privacy
-------
We may collect the following information from people visiting the website:

Feedback and comments that people leave, including email addresses, twitter usernames or Github usernames, depending on the method of communication.
Visitors’ IP addresses, and details of which browser they used.
Information on how people use the site, including the use of cookies.
The Data Cart feature uses the local storage facilities of your browser.
We don’t share your information with other organisations for commercial purposes and we don’t pass on your details to other parties, unless required to do so by law.
This site does not have advertisements.
```

**Comment by completer** [comment]
Accidentally closed - could you confirm @LynnHeeley ? Thanks.

**Comment by LynnHeeley** [comment]
fine - exaclty like the scot site - except we don't actually have a data cart facility to we?

**Comment by completer** [comment]
Please OK this @LynnHeeley  ?

**Comment by completer** [comment]
https://deli-lidar-beta.eu-west-1.elasticbeanstalk.com/

**Comment by completer** [comment]
OK'd by Lynn.
