### ISSUE TITLE
Lidar doc review

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/deli#55]

**Comment by LynnHeeley** [comment]
review the documentation with the idea that a data engineer could take on the data munging

**Comment by felixMasonJncc** [comment]
Docs here:
http://jncc-wiki/Projects_and_solutions/Scotland_LIDAR_Project?highlight=lidar

**Comment by felixMasonJncc** [comment]
Docs seem fine.
Probably someone with the following skills could use lidar.

- Experience trouble shooting spatial datasets in geospatial software and with command line gdal tools
- Familiarity with python. 
- Familiarity with running shell scripts on linux
- Some familiarity with using web apis and cloud based services
